### ISSUE TITLE
What is "base_path" in load_shader_module used for? 

### ISSUE THREAD

**Issue by slackers123** [elyshaffir/wgsl_preprocessor#5]
In the implementation of `load_shader_module`, the function takes `base_path` as an input but it is never used, why is that?

It seems like it was supposed to be concatenated with the `module_path`?

**Comment by elyshaffir** [comment]
This seems to be a bug, I marked this issue.

**Comment by elyshaffir** [comment]
If you'd like to remove it in your upcoming PR you can, just be sure to update this issue and I'll close it. If not it will probably be solved soon as it is fairly simple.
